services:
  - name: backend
    type: web
    env: docker
    plan: starter
    buildCommand: docker build -t backend ./backend
    startCommand: /wait-for-db.sh uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}

  - name: frontend
    type: web
    env: docker
    plan: starter
    buildCommand: docker build -t frontend ./frontend
    startCommand: yarn start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: ${BACKEND_URL}

  - name: db
    type: web
    env: docker
    plan: starter
    dockerfilePath: ./db/Dockerfile  # Asegúrate de que el Dockerfile exista si necesitas uno personalizado
    buildCommand: docker build -t db ./db
    startCommand: docker-entrypoint.sh mysqld
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}  # Asegúrate de que esta variable esté definida en tu entorno
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}  # Asegúrate de que esta variable esté definida en tu entorno
    # No se pueden definir volúmenes aquí, Render no lo soporta directamente.

# No definir volúmenes aquí, Render no lo soporta directamente.
